name: Run Node.js script on a schedule

on:
  push:
  schedule:
    # run at every hour
    - cron: "0 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - name: Start scraping
        run: npm start
        env:
          RASCHIETTO_BOT_TOKEN: ${{ secrets.RASCHIETTO_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          URL_TO_SCRAPE: ${{ secrets.URL_TO_SCRAPE }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update checksum file
